### ISSUE TITLE
[FEATURE] - Filter by Year

### ISSUE THREAD

**Issue by shadowtime2000** [damcclean/hacktoberfest-finder#185]
It would be great if you could filter by year on issues. Currently, I am finding issues from 2 years ago appear there, and those probably wouldn't be as maintained and willing to accept new pull requests.

**Comment by damcclean** [comment]
Good idea!

**Comment by johnhorsema** [comment]
Hi, I'm working on this issue. Please assign @johnhorsema.

It seems the dropdown change wasn't detected properly via computed properties.
I will add the year ago input for filter by **updated before the year**, since it's wh
at the Github Advanced Search provides:
<img width="737" alt="Screen Shot 2020-10-02 at 5 00 55 PM" src="https://user-images.githubusercontent.com/10090182/94906618-5ffca180-04d1-11eb-8b1b-9f0c0afd558a.png">

**Comment by damcclean** [comment]
Closed in favour of #187.
